### PR TITLE
8knot visualization heatmap notebook

### PR DESCRIPTION
**Pull request by cdolfi**
This is the first pass at the contributor heatmap visualization I have been working on for a while. This notebook is suppose to act as a work book to then build an 8knot visualization from. Let me know what yall think! Also would be great to have functionality feedback as well

### CODE REVIEW

**Comment by cdolfi** [comment]
Updated with image, the functional plotly graph in a running notebook looks a tad different

**Comment by cdolfi** [comment]
<p>Thats a question for @sgoggins but to my knowledge that is intended behavior</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1761810453'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>Pretty much this table gets recollected constantly and we need to just get the most recent collection. The two collections I saw that were the closest were 24 hours and 12 gives room to get all the files of the most recent collection. Realistically though these files are probably collected within minutes of each other in most cases, this was just the solution I can up with for the extremes</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1761810473'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>@sgoggins any insight here? For this use case though since there is a left join on the files and directories that currently exist those file paths are not represented further down in analysis</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1761810487'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>Hm im not sure if im following what you are saying or if its just a different application of this type of analysis. This plots for each contributor on the file or directory how long its been since they have been active in any way on any part of the code base. The intention of this is to see if there are areas of the codebase that do not have or limited number of contributors/reviewers that are familiar with the code  </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1761810572'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>X axis: completely agree I actually had that set up but didnt see in the final result that it got flipped again </p><p>y axis: I personally prefer on the left hand side for the same reason that you give for the x axis. Something we can discuss more later. </p><p> </p><p>Going to start implementing the code to select a file and get the contents of it. </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1761810589'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sgoggins** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1761810453) on ReviewNB
> 
> _JamesKunstle commented on 2023-10-13T16:45:30Z_ ----------------------------------------------------------------
> 
> Is the 'repo_path' column bugged? github.com-chaoss-augur should be 'github.com/chaoss/augur' right?
> 
> _cdolfi commented on 2023-10-16T17:54:41Z_ ----------------------------------------------------------------
> 
> Thats a question for @sgoggins but to my knowledge that is intended behavior

THe path is the local file path on the server. If you want the GitHub URL, that is in the repo table.

**Comment by cdolfi** [comment]
@JamesKunstle ready for rereview

**Comment by sgoggins** [comment]
<p>repo_path is a proxy for part of the folder name. If you want the url for the repo, that is in the repo_git field in repo. </p><p> </p><p>The reason for this is because when people add, for example, one repo from an org, that repo would go in a directory for just that org; then, when repos move, the directory would make no sense. So, we simplified the directory structure. You will see in the file_path that the directory structure is common, with the root of the cloned repo in the <code>repo_root</code> parameter directory in augur_operations.config table, so the "file path ends up being: <code>repo_root/repo_id/repo_path</code> on the hard drive where repos are stored.     </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1761810453'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sgoggins** [comment]
<p>@JamesKunstle and @cdolfi: I use <code>max(data_collection_date)</code> to get only the most recent for each file. Here's an example query you'd probably want converted to a view: </p><p> </p><p><code></code><code>sql</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SELECT</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;e.repo_id,</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;augur_data.repo.repo_git,</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;augur_data.repo.repo_name,</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;e.programming_language,</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;e.code_lines,</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;e.files</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FROM</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;augur_data.repo,</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(SELECT </p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;d.repo_id,</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;d.programming_language,</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SUM(d.code_lines) AS code_lines,</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;COUNT(*)::int AS files</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FROM</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(SELECT</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;augur_data.repo_labor.repo_id,</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;augur_data.repo_labor.programming_language,</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;augur_data.repo_labor.code_lines</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FROM</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;augur_data.repo_labor,</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;( SELECT </p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;augur_data.repo_labor.repo_id,</p><h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>&nbsp;MAX ( data_collection_date ) AS last_collecte</strong>d</h3><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FROM </p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;augur_data.repo_labor</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;GROUP BY augur_data.repo_labor.repo_id) recent </p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;WHERE</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;augur_data.repo_labor.repo_id = recent.repo_id</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AND augur_data.repo_labor.data_collection_date &gt; recent.last_collected - (5 * interval '1 minute')) d</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;GROUP BY d.repo_id, d.programming_language) e</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;WHERE augur_data.repo.repo_id = e.repo_id</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ORDER BY e.repo_id</p><p></code><code></code> </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1761810473'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sgoggins** [comment]
<p>Note: I still have the interval in there, which exists because not every file is going to be processed in the same minute, but will be processed in less than 5 minutes. </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1761810473'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>@sgoggins What would be the benefit of using a more complicated query in this case? </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1761810473'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>We can talk through this more but I dont agree. This histogram would be applied to any directory/folder not just top level and I think there is a benefit to seeing the individual files if they are listed in the top level of each directory/folder. This allows the ability to see each file individually if they go far enough in. Maybe a future iteration is a "file grouping mode" </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1766856249'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>So that'd be the real name of a directory then?</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1761810487'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>I think it's a different application altogether. </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1761810572'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>++ I agree w/ Cali- we want to be able to descend the tree and look at each file individually</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1766856249'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>Would you be able to open an issue detailing this idea? </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1761810572'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>Yeah definitely</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1761810572'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1761810589) on ReviewNB
> 
> _JamesKunstle commented on 2023-10-13T16:45:37Z_ ----------------------------------------------------------------
> 
> This is very cool!
> 
> One thought I have is that we can implement a "drill down" mode, where we default to showing the top-level and use the on-click property of the graph to allow the user to click on the y-axis values, which will then rebuild the heatmap if the value is a folder, with respect to its contents.
> 
> You're already tracking the nested structure in 'df_file', so if a user clicked on 'docs' then you could screen for files where column '0' was 'docs,' tracking which 'level' you're currently at over time.
> 
> I have two comments on figure design: I'd swap the x-axis to be earlier->more recent, and I'd have the y-axis on the righthand side. I was a bit confused on the date range on initial inspection- my brain wants to read left to right.
> 
> 
> _cdolfi commented on 2023-10-16T18:10:50Z_ ----------------------------------------------------------------
> 
> X axis: I can show the other option but the reason I flipped the axis was that having the most recent dates (more color = good) on the right side was for interpretability and did not look good visually to me for the same reasons you describe for the dates. Two different applications of the same intuition. Run the notebook without the "fig['layout']['xaxis']['autorange'] = "reversed"" line and see what you think
> 
> y axis: I personally prefer on the left hand side for the same reason that you give for the x axis. Something we can discuss more later.
> 
> Going to start implementing the code to select a file and get the contents of it.

@JamesKunstle talking to greg you and him came to the same visual conclusion separately so I feel good moving forward with it. Looking at moving the color legend to the left side and everything else on the right

**Comment by cdolfi** [comment]
<p>I see a user using this to determine potential "risks" in the codebase from a maintainer perspective. This visualization will be able to tell you of the people who have contributed (or review in the other view) to the file or directory when they were last "seen" in the project. Then a more proactive knowledge share can happen instead of stumbling upon it when there is a pile up of issues, prs, etc happen around the file and there is little to no people who understand the code </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1769511665'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jberkus** [comment]
So, questions:

1. Am I correct that the purpose of this heatmap is to find "hotspot files" that keep getting touched by a lot of people?  With the idea that we could also combine that with a list of who is authorized to review those files, and find bottlenecks?

2. If a project has thousands of files, which ones would be displayed?

3. How is LOC used in this analysis?

**Comment by cdolfi** [comment]
1. I actually made it with the intention of finding files that have "brain drain" ie most/all contributors that have touched the file priorly have not be active in any part of the code base for an extended period of time. This will also be repeated for reviewers as a separate visualization. I like the idea creating another visualization where it is showing a heatmap of activity on the file overall, if you could create an issue detailing the idea thatd be awesome if not I can open one with my interpretation as well. 
2. Right now my implementation idea is for the user to be able to select a directory to look at and that is what will populate the heatmap. Open to other ideas as well, thats part of the discussion i am hoping to have on this PR 
3. LOC as in Lines of code changes? If so then not at all. This heatmap takes all of the the prior contributors to a specifc file or subdirectory and plots their "last seen" timestamp from any part of the repository

**Comment by JamesKunstle** [comment]
<p>That makes sense. This visualization is pretty difficult to interpret without the kind of explanation you just provided. We should break from our existing guidelines and provide an example of usage in the 'About' window to clarify.</p><p> </p><p>It'd also be interesting to highlight those areas of the codebase (files, folders?) for which the historic contributors haven't been seen in a while, maybe via a ranking in descending order of recency? This would be a separate visualization.</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1769511665'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
@cdolfi Coming back to this viz after some rest- I see the intention and utility much more clearly. My only current review comments are:

1. I still think left-to-right over time on the x-axis is clearest (which I believe Greg also said, and that you're moving forward with).

2. I don't know how to reconcile this, but the 'heatmap' component of the visualization is somewhat challenging to interpret. "redder" means **worse** as we go back in time, and **better** as we get closer to 'now'. I'm not sure how to fix that- maybe it's just a change of color? Red often means bad, whereas the green spectrum (light to dark) somehow feels more like volume, and less like a description of 'goodness' to me. IDK just mentioning.

Having read the code thoroughly this review, I'm going to take a step back and re-review for analysis (Pandas) correctness again soon, but generally everything seems reasonable to me.

I'm in agreement w/ Josh's first point, though. I opened an issue with the same general idea. Seeing a raster-plot of activity over time at the directory level and below would be very interesting.

**Comment by jberkus** [comment]
1. I think there are several things we could see with this analysis.  Like:
a. what files are touched frequently, but very few people ever review/approve?  (my original use-case)
b. what files are touched frequently, and don't have good test coverage?
c. what large code files haven't been touched in years and should probably be audited?
d. what files used to be touched frequently, but aren't anymore, and the touchers have left the project (your use-case)

2. I think being able to look at an individual directory is good.  The other views that would be good would be:
a. all files in the repo, ranked (so we get the "top 25" in the default view)
b. by directory in the repo, instead of individual files

3. I just asked about LOC because you pull that info in your query

**Comment by cdolfi** [comment]
@JamesKunstle  
1. Yes moving forward with the flip of axis
2. Color should not be as much of an issue on 8knot, it will be implemented using our color pallet 

Sounds good on the correctness review. Definitely need another set of eyes there is a lot going on

@jberkus  
1. I like the list out of use cases. Will add to the jupyternotebook for we have documentation for it to go into the "graph info" tag on 8knot. goes well with what @JamesKunstle was saying
3. Ah yes no LOC use in this viz but could see one on different visualization extensions from this

**Comment by jberkus** [comment]
I'm not sure how we *should* use LOC.   It's not obvious; bigger files/patches aren't necessarily more critical (or less critical).

**Comment by cdolfi** [comment]
<p>It would be a really rare scenario where the there is a file name that is also a directory. It would require a file that doesnt have a ".xx" (file type), and the same capitalization</p><p> </p><p>The strategy you mention above would only get the top level directories. </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1787674118'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>Going to change from str.contains to str.startswith to prevent this issue</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1787674160'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>Hm so its suppose to be the data to go into a figure. If you have another naming suggestion id be more than happy to switch it, in the 8knot code this naming wont be used, just use different names for dfs at different steps to be able to see the transformation of the data in the notebook </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1787674204'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>It actually is a column for each month, see the printout of the df after the groupby </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1787674239'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>Agreed, we will have to think alot about the "Graph info" tag. IMO the concept is actually pretty concise but difficult to explain/interpret. But once you get it its decently simple. Will definitely need to bring in some different opinions to really get the wording right </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1787674272'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>++ that seems like a good patch, all pathnames are guaranteed to be unique.</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1787674160'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>yeah I guess plot_data would be fine- 'plot' and 'figure' and 'fig' seem to always be for visualization objects.</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1787674204'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>++ agreed. In practice the visualization is definitely clarifying, especially above now that I all of the directories in the toplevel of augur are visible. Very cool.</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/234/discussion/#comment-1787674272'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
@cdolfi anything else pre-merge? I think this notebook is clear to go

**Comment by cdolfi** [comment]
@JamesKunstle nope good to go on my end!

**Review by JamesKunstle — APPROVED** [review]

**Pull request merged**
