### PR TITLE
community dynamics analysis demo app

### PR DESCRIPTION
**Pull request by mariashev**
Created an interactive dashboard with the goal to provide users with data-driven insights into the behavior of their open source project's contributors. The dashboard includes 4 visualizations: a network graph showing the connectivity of contributors and three complementary plots tracking various trends over time. 

Added README.md file to aid in contribution, use, and understanding of the dashboard

### CODE REVIEW

**Comment by JamesKunstle** [comment]
@mariashev I'm playing with the app and I have to say, this is super cool. It's pretty quick too! 

I'm kinda voting that this get merged at this stage- there are two thing that need to happen first, though.

First, please wrap the graphs in dcc.Loading objects. Knowing when something is loading is very convenient.
Second, please specify which repos/orgs are valid with an informative hover or tile. I used chaoss/augur and ansible/ansible, but I'd like to know which other options are available.

Other than that, your Readme and code look great, and we can use the graph_utils directory nicely.

@cdolfi Lemme know what you think.

**Comment by JamesKunstle** [comment]
@mariashev I also got this error, though, looking for the top 50 contributors in a project:

```
Traceback (most recent call last):
  File "/Users/jkunstle/Documents/Rappel/demo_apps/community_dynamics_analysis/components/plots/plots_helper.py", line 51, in get_plot_data
    threshold_score = find_threshold(np.array(list(pagerank_scores.values())), threshold)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkunstle/Documents/Rappel/demo_apps/community_dynamics_analysis/graph_utils/graph_helper.py", line 56, in find_threshold
    threshold_score = scores[-threshold[1]]
                      ^^^^^^^^^^^^^^^^^^^^^
IndexError: index -50 is out of bounds for axis 0 with size 28
```

**Comment by cdolfi** [comment]
@JamesKunstle @mariashev Agree with james, once those errors are fixed I am good with merging

**Comment by JamesKunstle** [comment]
@cdolfi @mariashev Ye, to me this PR is done. Very awesome to use too, I'm excited to integrate this into 8Knot.

**Pull request merged**
