### PR TITLE
AI Repo analysis

### PR DESCRIPTION
**Pull request by Prudhvivuda**
This PR contains the files and code for the AI repositories analyses to find the contributions to the AI repositories and represent the contributions in the graphical format.

WIP as there is still data that needs to be collected

### CODE REVIEW

**Comment by cdolfi** [comment]
@Prudhvivuda Add in some context in your PR description of what this PR is and the WIP nature of it with the data still being collected. Also next PR tag myself and James as reviewer (I added it for this one)

**Review by cdolfi — CHANGES_REQUESTED** [review]
Requested changes from reviewnb comments. Overall this is a fantastic first PR, let me know when the changes are in and Ill review again

**Comment by Prudhvivuda** [comment]
<p>No. There are no None's. All the commits have cntrb_id mapped to it.</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330055'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>okay</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330074'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330094'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330114'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330134'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330158'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330173'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>okay</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330195'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>okay</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330235'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>ok</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330360'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>sure</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330470'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>Ok. Initially added labels but it really messed up the whole graph. Now figured out a way to add labels only to the repositories.</p><p>Added the analysis for the connections/contributions with 3 or more repositories</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330261'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>is there any information on the types and number of tables available? I removed the limit.</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330031'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p><a href="https://oss-augur.readthedocs.io/en/main/schema/overview.html" target="_blank">https://oss-augur.readthedocs.io/en/main/schema/overview.html</a> heres an overview of the schemas. We usually use pull_requests table for what you are doing above. @sgoggins would be able to say more about the differences between the two</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330031'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>Looks great! Is there any way to add background to the text so it is fully visible </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330285'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>With contributions having such a specific meeting, the term contributions should not be used in this context. Id use just "shared contributors" or a different not overloaded term </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330422'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>okay. Got it</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330422'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>Done!</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330285'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>I tried to use pull_requests but the table pull_requests doesn't have contrb_id stored in it. So I used pull_request_meta table.</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330031'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
notebook updated. @cdolfi Could you review?

**Comment by cdolfi** [comment]
<p>in pull_requests the cntrb_id is named "pr_augur_contributor_id". @sgoggins, is there any difference between the data in pull_request_meta and pull_requests in this use case? </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330031'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>(discussion for the query for pull requests above this one)</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330031'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>removed double "shared" </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330422'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by cdolfi — CHANGES_REQUESTED** [review]
A few more small changes and then re-run the notebook with the new data

**Comment by sgoggins** [comment]
<p>Connections are the key construct. I understand these are sociograms constructed by showing contributors and the repositories they contribute to within the set under analysis. </p><p>Clustering is a word that is usually operationalized using data other than connections. I am not saying the graphs do not show clusters, only that the graphs illustrate groups of connected people and projects in some scope. Use of the word cluster may confuse the reader. Or not. :) </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330011'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sgoggins** [comment]
<p>@cali : No that is evidence of dumbness on my part on a day. We should probably open an issue to refactor it, but I'm hoping a future version of PostgreSQL has a column renaming feature instead of forcing us to dump the table and reload it ... which is a risky endeavor to script ... </p><p> </p><p>tl;dr -  yes: pr_augur_contributor_id is EXACTLY the same as cntrb_id in other tables. </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330031'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sgoggins** [comment]
<p>There are 1,007 records in unresolved_commit_contributors (and 175,749 contributors records) ... So, you are missing some number of commits from those users. These missing contributors are a small and somewhat random fraction, and more often associated with older commits. </p><p> </p><p>I verified the query with a similar one that could be a bit more robust, but functionally these queries return EXACTLY the same number of rows, so I think you're good. </p><p> </p><p><code></code><code>sql</p><p>SELECT r.repo_id,</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;r.repo_name,</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;r.repo_git,</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;c.cmt_ght_author_id,</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;c.cmt_id</p><p>FROM</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;repo r, commits c</p><p>WHERE</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;c.repo_id = 1 AND</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;c.repo_id = r.repo_id and</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;c.cmt_committer_email in </p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(select alias_email as email</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from contributors_aliases</p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;union </p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;select </p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cntrb_email as email </p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from contributors where </p><p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cntrb_email is not NULL); </p><p> </p><p> </p><p>SELECT r.repo_id,</p><p>r.repo_name,</p><p>r.repo_git,</p><p>ca.cntrb_id,</p><p>c.cmt_id</p><p>FROM</p><p>repo r, commits c, contributors_aliases ca</p><p>WHERE</p><p>c.repo_id = 1 AND</p><p>c.repo_id = r.repo_id and</p><p>c.cmt_committer_email = ca.alias_email;</p><p></code><code></code></p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330055'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sgoggins** [comment]
<p>@cdolfi ' ssuggestion could be accomplished by using a contributor count statistic for each community as a scaling factor for node size. </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330470'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sgoggins** [comment]
<p>Are these just different nodes than the prior one? </p><p> </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2240074301'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sgoggins** [comment]
<p>The commits table has 1 row per file in a commit. To get the commit count you need to do something like this (which you may already be doing):</p><p><code></code><code>sql</p><p>select repo_id, count(*) from </p><p>(</p><p>select repo_id, cmt_commit_hash, count(*) </p><p>from commits where repo_id =1</p><p>group by repo_id, cmt_commit_hash) group by repo_id; </p><p></code><code></code></p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2246276409'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by sgoggins** [comment]
<p>I can't see the underlying query logic, but my previous comment may help ... something is a bit awry with duplicate cntrb_ids though. I agree with @cdolfi</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2246276425'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by sgoggins — COMMENTED** [review]
See my notes in the Jupyter Notebook review system.

**Review by hemajv — CHANGES_REQUESTED** [review]
Nice work on the notebook @Prudhvivuda! I've left my review, ptal

**Comment by Prudhvivuda** [comment]
<p>acknowledged! I have changed the table from pull_request_meta to pull_requests</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330031'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>Thank you for the suggestion, Sean. I have changed it.</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330011'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>okay</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2234330055'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2246276400'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>How to know if something is a GH webhook like 01012f1b-7f00-0000-0000-000000000000?</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2246276409'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>they are the same</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2240074301'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>okay</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2251166593'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2251166612'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2251166673'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2251166637'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2251166696'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>change the variable names as well to be generalized (not using commit) </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2246276400'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>not sure if this is what @hemajv was talking about. Usually a section summary would be a few sentences </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/253/discussion/#comment-2251166637'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
@Prudhvivuda Not able to open Reviewnb for some reason. Take our the empty cells and squash your commits and it will be good to merge!

**Review by cdolfi — APPROVED** [review]
lgtm

**Pull request merged**
