### PR TITLE
Alpha beta implementation

### PR DESCRIPTION
**Pull request by JamesKunstle**
rebased on top of PR #230. Extends notebook with implementations of alpha and beta terms.

- alpha: the multiplier by which our subpopulation of interest is more or less likely to contribute to a given repo.
- beta: alpha, scaled by the real magnitude of the contribution of the subpopulation.

New work is below section: 
Implement alpha and beta indices of preference

Formulation and discussion here:
https://www.overleaf.com/read/hxnsqsydqcrw

### CODE REVIEW

**Review by cdolfi — APPROVED** [review]
lgtm! Looks like most of this is content we have reviewed on other PRs

**Review by oindrillac — COMMENTED** [review]
Love to see the implementation of your logic! Thanks @JamesKunstle

**Comment by hemajv** [comment]
<p>++ I also think a brief explanation of what alpha/beta is and why we are defining it would be useful here</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/238/discussion/#comment-1759529078'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by hemajv — CHANGES_REQUESTED** [review]
@JamesKunstle awesome work 👏  I really liked the way you explained it mathematically 💯 

I've left a few comments, do take a look!

**Comment by JamesKunstle** [comment]
<p>I'll be rebasing this notebook only the final merged 'repo_discovery' notebook that has a longer conclusion at the end here, describing this figure and noting some ideas for next steps, including those reported below.</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/238/discussion/#comment-1759528975'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>++</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/238/discussion/#comment-1759529078'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>yep!</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/238/discussion/#comment-1762052280'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>yes absolutely</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/238/discussion/#comment-1762052301'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>added in revision</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/238/discussion/#comment-1781496661'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>++</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/238/discussion/#comment-1759529129'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>++</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/238/discussion/#comment-1762052321'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>++</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/238/discussion/#comment-1762052355'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>++</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/238/discussion/#comment-1759529197'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>++</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/238/discussion/#comment-1762052392'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by hemajv — APPROVED** [review]
The new changes look good, thanks @JamesKunstle! Good to merge this once it is rebased after #230 is merged

**Review by oindrillac — APPROVED** [review]
This was very easy to read through. Thanks @JamesKunstle

**Comment by JamesKunstle** [comment]
@cdolfi rebased on repo_discovery branch

**Pull request merged**
