### PR TITLE
Common Contributors across AI fields

### PR DESCRIPTION
**Pull request by Prudhvivuda**
In this notebook, we will try to plot the graphs for each category(math, nlp, llm, gen_ai, personal_assistants) in the AI/ML we defined earlier.

### CODE REVIEW

**Comment by Prudhvivuda** [comment]
<p>Changed the name</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/259/discussion/#comment-2311132541'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/259/discussion/#comment-2311132640'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>don4</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/259/discussion/#comment-2311132626'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>removed.</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/259/discussion/#comment-2311132615'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>okay</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/259/discussion/#comment-2311132591'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
@Prudhvivuda Great job, lot of improvement this review cycle

**Comment by Prudhvivuda** [comment]
<p>Should I just copy the takeaways from each section and paste it here?</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/259/discussion/#comment-2318846300'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>yes</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/259/discussion/#comment-2318846300'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/259/discussion/#comment-2318846300'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by dominikkawka — APPROVED** [review]
LGTM, 

Although there could always be more communities added, there is a healthy amount present. The only 'large' community missing (to my knowledge) right now is scikit-learn.

**Review by hemajv — CHANGES_REQUESTED** [review]
@Prudhvivuda great notebook! I've left a few comments, ptal

**Comment by cdolfi** [comment]
<p> </p><p> </p><p>Does every key value pair only have 1 repo? If not show an output of examples with variable length</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/259/discussion/#comment-2339336542'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>No. There are key value pairs with more than 1 repo. Changed the code to print first 15 items. Now it contains at least 1 item with more than 1 repo as a value for a key.</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/259/discussion/#comment-2355200292'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>No. There are key value pairs with more than 1 repo. Changed the code to print first 15 items. Now it contains at least 1 item with more than 1 repo as a value for a key.</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/259/discussion/#comment-2339336542'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>Yes, it includes both open and closed PRs. </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/259/discussion/#comment-2339336376'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>This was expected with the old code. I rewrote small code to write the image to a file and display. Now, it should render in the notebook.</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/259/discussion/#comment-2339336607'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by cdolfi — APPROVED** [review]
lgtm

**Pull request merged**
