### PR TITLE
Add recency and tf-idf weighted edges demo nb

### PR DESCRIPTION
**Pull request by christinaexyou**
@JamesKunstle addresses #216 by demonstrating the `preprocess`,`calc_recency_weights` and `calc_tfidf_weights` methods in `graph_helper_functions.ipynb`.

* Outlines logic of recency and TF-TDF weights
* Visualizes two separate contributor-repository graphs with edges weighted by recency and TF-IDF

cc: @hemajv @oindrillac

### CODE REVIEW

**Comment by cdolfi** [comment]
@christinaexyou what is the difference between this and #236?

**Comment by christinaexyou** [comment]
@cdolfi this PR walks through the logic/use cases of the the changes made in #236 to give more context. However, I'm not sure if we want to include in Rappel yet which is why I made a separate PR, waiting for feedback.

**Comment by christinaexyou** [comment]
<p>It means that 71292 has a high issue volume contribution from a large set of contributors that create significantly less issues in other repos in the group. A dark edge or a relatively high TF-IDF value <strong>can</strong> indicate if a contributor has specialized knowledge since it means that they're contributing significantly to a single repo. Repo 71292 corresponds to the PyTorch Operator in KubeFlow which requires specialized knowledge of PyTorch. But given that we're looking at issues created, I doubt that every "focused" issue contributor has specialized knowledge. </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/243/discussion/#comment-1810923939'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
@christinaexyou I read through this very carefully as well- thanks for your clarification, I think this is well put together and I want to merge it.

**Pull request merged**
