### PR TITLE
Growth rate calculation

### PR DESCRIPTION
**Pull request by Prudhvivuda**
In this PR, I'm trying to apply models to calculate the growth rate of the projects.
- [x] Calculate the age of projects
- [x] Calculate growth rate for the last 6 months

### CODE REVIEW

**Comment by Prudhvivuda** [comment]
<p>ok. done</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/262/discussion/#comment-2465040587'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/262/discussion/#comment-2465040546'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/262/discussion/#comment-2465040519'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>ok</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/262/discussion/#comment-2465040479'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
@Prudhvivuda meet with @dominikkawka to see from a consumer perspective what is informative or necessary context to get there for the next notebook

**Comment by Prudhvivuda** [comment]
<p>Done. Thank you.</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/262/discussion/#comment-2469065446'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
<p>For some repositories the decay factor was close to 0 that were older than 50 and for the repositories that were even older, the decay factor was something like 2.610298031214378e-13. In the first 6 months, for most of the repositories there was only commit contribution and other contributions were either 0 or negligeable (which was expected as in the initial stages only commit and reviews were expected). So, when we calculate the decay factor using (0.9)^age, the numbers were too small. </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/262/discussion/#comment-2469065404'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
> For some repositories the decay factor was close to 0 that were older than 50 and for the repositories that were even older, the decay factor was something like 2.610298031214378e-13. In the first 6 months, for most of the repositories there was only commit contribution and other contributions were either 0 or negligeable (which was expected as in the initial stages only commit and reviews were expected). So, when we calculate the decay factor using (0.9)^age, the numbers were too small.
> 
> [View entire conversation](https://app.reviewnb.com/oss-aspen/Rappel/pull/262/discussion/#comment-2469065404) on ReviewNB

If I zoom in near the y axis at 0, then I can see some of the lines for some repositories.

image

**Comment by cdolfi** [comment]
<p>If thats the case should each of those months plot at zero? Not having them at all is very confusing </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/262/discussion/#comment-2469065404'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Prudhvivuda** [comment]
> If thats the case should each of those months plot at zero? Not having them at all is very confusing
> 
> [View entire conversation](https://app.reviewnb.com/oss-aspen/Rappel/pull/262/discussion/#comment-2469065404) on ReviewNB

As I said, we can see them if we zoom in. They are all around 0 which seems to be like a single line at y-axis=0.

**Review by cdolfi — CHANGES_REQUESTED** [review]
Please squash commits and will be good to merge!

**Review by cdolfi — APPROVED** [review]
lgtm

**Pull request merged**
