### PR TITLE
wasm collaboration network first pass

### PR DESCRIPTION
**Pull request by JamesKunstle**
adds utility of joining two or more repo networks in the context of some general WASM projects, suggests next steps for improvement.

### CODE REVIEW

**Comment by JamesKunstle** [comment]
<p>No it was arbitrary. This notebook isn't <em>really </em>trying to be experimental, just demonstrate the technique of combining networks, so I picked a few preeminent projects within scope.</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/228/discussion/#comment-1719610575'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>++ need to clarify this.</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/228/discussion/#comment-1719610608'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>++</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/228/discussion/#comment-1719610634'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>wasi was failing for some reason so I just removed it for consideration. </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/228/discussion/#comment-1719610655'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>++ Yeah definitely </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/228/discussion/#comment-1719610775'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>++</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/228/discussion/#comment-1719610737'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
@cdolfi updated PR

**Comment by cdolfi** [comment]
<p>got it</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/228/discussion/#comment-1719610575'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>Makes sense, lets open an issue to look into this to see why/ make sure there is nothing bigger happening w that repos data</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/228/discussion/#comment-1719610655'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>Can you add the legend to the picture?</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/228/discussion/#comment-1719610737'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>Adding a legend is actually a really complicated process for this many nodes, unfortunately, so I'd rather make a note and merge this PR than spend the time hacking the legend in- are you amenable to that?</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/228/discussion/#comment-1719610737'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>Sounds good to me!</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/228/discussion/#comment-1719610737'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by hemajv** [comment]
@JamesKunstle @mariashev great work on the collaboration network analysis 🎉 
@JamesKunstle reviewed the notebook and left a few comments

**Comment by JamesKunstle** [comment]
<p>Yes exactly. The nodes of the merged network are the union of the nodes of the two networks.</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/228/discussion/#comment-1730229293'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>replaced 'community' with 'repo'</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/228/discussion/#comment-1729532036'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>++ sounds great</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/228/discussion/#comment-1729532057'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
@hemajv @oindrillac @cdolfi responded to PR

**Review by cdolfi — APPROVED** [review]
lgtm! Good to merge once oindrilla and hema take a look

**Review by oindrillac — APPROVED** [review]
LGTM! thanks @JamesKunstle

**Comment by sgoggins** [comment]
@JamesKunstle : I'm running your fork and get an error that this notebook does not exist: `Whole-Game-Arg-Feature-Processing.ipynb`

**Comment by JamesKunstle** [comment]
@sgoggins uhhhh weird. I'll look into that.

**Review by hemajv — APPROVED** [review]
thanks for addressing the comments @JamesKunstle!
/lgtm 👍

**Comment by JamesKunstle** [comment]
@sgoggins I definitely don't get that error. Are you getting it when you boot this notebook and try to run it?

**Pull request merged**
