### PR TITLE
Contributor and repository graph analysis

### PR DESCRIPTION
**Pull request by oindrillac**
In this PR, we created initial graph representations of existing open source GitHub repositories falling under a certain category using [NetworkX](https://networkx.org/). 

related https://github.com/sandiego-rh/Rappel/issues/168

We created 2 type of graph representations from the same data:

- One where repositories and contributors both are both nodes (differently colored). Viewing which repositories share which set of contributors and analyzing their clusters can give an idea about how projects are connected to each other and to what degree 

Screen Shot 2022-10-27 at 8 45 12 PM

- One where repositories are nodes, and edges are number of contributions. The distance between repositories, how close or far they are will depend on the number of shared contributions that exist between them, and how well connected projects are with each other.
Screen Shot 2022-10-27 at 8 44 54 PM

### CODE REVIEW

**Comment by oindrillac** [comment]
<p>I agree with this. Will rename this, cleaner than having spaces in the names.</p>

---

 <a href='https://app.reviewnb.com/sandiego-rh/Rappel/pull/175/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by oindrillac** [comment]
<p>That's a very good point. Will see how we can extend this work to include the Authors as well.</p>

---

 <a href='https://app.reviewnb.com/sandiego-rh/Rappel/pull/175/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by oindrillac** [comment]
<p>Yes absolutely. Intend to add more explanation, examples and samples with this https://github.com/sandiego-rh/Rappel/issues/174 but even at this phase, going to add some in-depth comments/annotation to improve readability</p>

---

 <a href='https://app.reviewnb.com/sandiego-rh/Rappel/pull/175/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by oindrillac** [comment]
<p>No this is not a complete (fully-connected) graph. All nodes do not have a direct connection to each node. But each node has <strong>atleast one connection</strong>. Similar to a social media platform where the requirement to be on the network would be to have atleast one connection. For example - see project node '27034' and '27032', they are not connected as they do not have any shared contributors.</p><p> </p><p>To your previous comment, along with details on how we got to this graph, I will also add some comments on how this graph can be interpreted.</p>

---

 <a href='https://app.reviewnb.com/sandiego-rh/Rappel/pull/175/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by oindrillac** [comment]
<p>Right! That makes me think, it would be cool to dynamic plotly like graphs from these where we can hover over these to see metadata on these nodes etc </p>

---

 <a href='https://app.reviewnb.com/sandiego-rh/Rappel/pull/175/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by oindrillac** [comment]
<p>Would be cool to have dynamic graph here too, so one can hover over the edges to see "which contributors" constitute these shared contributors. Would be so nice to be able to drill down into those views.</p>

---

 <a href='https://app.reviewnb.com/sandiego-rh/Rappel/pull/175/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>Is the coloring here the same as above? blue for repo and yellow for contributor? </p>

---

 <a href='https://app.reviewnb.com/sandiego-rh/Rappel/pull/175/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>For the edge lengths here what do they specifically correlate to?</p>

---

 <a href='https://app.reviewnb.com/sandiego-rh/Rappel/pull/175/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by oindrillac** [comment]
<p>Created an issue to address this https://github.com/sandiego-rh/Rappel/issues/177</p>

---

 <a href='https://app.reviewnb.com/sandiego-rh/Rappel/pull/175/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by oindrillac** [comment]
<p>Added some explanation for these transformations and the graphs.</p>

---

 <a href='https://app.reviewnb.com/sandiego-rh/Rappel/pull/175/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by oindrillac** [comment]
<p>@cdolfi the edge lengths here correlate to the number of shared contributions amongst them. Added some explanations for the graph below for more clarity.</p>

---

 <a href='https://app.reviewnb.com/sandiego-rh/Rappel/pull/175/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by oindrillac** [comment]
@cdolfi @JamesKunstle added some more annotations and explanations to the notebook. Please take a look

**Comment by oindrillac** [comment]
> Is the coloring here the same as above? blue for repo and yellow for contributor?
> 
> [View entire conversation](https://app.reviewnb.com/sandiego-rh/Rappel/pull/175/discussion/) on ReviewNB

Yes, thats correct. Added legends to each graph for clarity

**Comment by oindrillac** [comment]
Just want to bump this up. Comments above were addressed and this is ready for another look.

**Review by cdolfi — APPROVED** [review]
lgtm! @JamesKunstle What do you think?

**Comment by JamesKunstle** [comment]
big lgtm from me

**Review by JamesKunstle — APPROVED** [review]
lgtm

**Pull request merged**
