### PR TITLE
project velocity discussion

### PR DESCRIPTION
**Pull request by cdolfi**
This notebook sets up everything to be able to discuss the specifics for the project velocity visualization

### CODE REVIEW

**Comment by JamesKunstle** [comment]
@cdolfi 
So, I found where the definition has been applied in the CNCF's work:
https://github.com/cncf/velocity

I also found the source article where this is talked about:
https://www.cncf.io/blog/2017/06/05/30-highest-velocity-open-source-projects/

Both sources are in the CHAOSS definition page:
https://chaoss.community/kb/metric-project-velocity/

The x and y axes are 'log # commits' and 'log (# prs + # issues)' I think, in the CNCF script. They appear to make no distinction between open, closed, merged, (etc.) PRs and Issues.

The data they get from BigQuery isn't very discerning.
e.g.
`org,repo,activity,comments,prs,commits,issues,authors
kubernetes,kubernetes/kubernetes,11243,9878,720,70,575,40
ethereum,ethereum/go-ethereum,10701,570,109,43,9979,14
...`

The script that the analysis is done in isn't commented much, and is in Ruby, so I'm not entirely sure if they may any distinction. 

That being said, reading the CHAOSS definition, Velocity seems to want to capture a snapshot of the state of projects at time 'T' with the motivation being, quote Dan Kohn:

"...most developers are interested in using and participating in the largest projects, and the projects with the most developers are more likely to quickly fix bugs, add features and work reliably across the largest number of platforms."

My reading of the spirit of the definition is that, at time T, the number of pull requests *made* (opened + merged + closed_unmerged) and issues *made* (open + close) is most appropriate. If the assumption of the Velocity paradigm is that larger, more active projects are more likely to experience increasing returns of scale (more people are going to want to join highly active projects) then these all-including axes make the most sense to me.

An extension of this thinking is to use time-window based analysis in a future iteration which will allow us to discount earlier activity if a project at time T is much less active than at time 't', thereby the volume of time 't' doesn't overrepresent the current activity.

Velocity seems pretty reasonable in that respect- PRs are made, merged, closed, etc. and it's all signal implying activity and engagement. Those projects that do dramatically more "engagement" stuff will have higher churn or direct net-new development that (to my intuition) are more likely to attract new people, meriting inspection.

**Comment by cdolfi** [comment]
@JamesKunstle For me "pull requests or issue made" would be just opening a pull request or issue. Merged or Closed are actions done on said pull request. With that, I am more concerned with this visualization being the most informative than it following any specific definition elsewhere. With that ill apply adding all of those together and see what the results are like

**Comment by JamesKunstle** [comment]
@cdolfi 
I don't think I was specific enough in my description of a definition: each count would just be concerning the existence of a pull request that was made. This includes PRs that are in any state at time 'T', including "currently open", "has been merged", and "has been closed without merging". Which is equal to the total number of pull requests ever opened. Same for issues.

**Comment by cdolfi** [comment]
@JamesKunstle Ah I see what you are saying. After thinking about the "...most developers are interested in using and participating in the largest projects..." quote I actually could see some potential value in including all of those actions as it does represent a trend towards overall progression of bugs fixed, features implemented all the way through. I have some ideas. I am going to implement a few different interpretations on this and push those updates so we can check them out. Really liking this process of collaboration on a more complicated visualization, the time to go into implementing different strategies is actually super quick

**Comment by cdolfi** [comment]
@JamesKunstle Quick follow up: Do you have anything specific on the x axis I should try besides log of commits? Everything I am thinking of/ weve been discussing (I believe) has been about the y axis

**Comment by cdolfi** [comment]
New strategies implemented, very curious to hear peoples thoughts on them or others to try

**Comment by JamesKunstle** [comment]
> @JamesKunstle Quick follow up: Do you have anything specific on the x axis I should try besides log of commits? Everything I am thinking of/ weve been discussing (I believe) has been about the y axis

I totally missed this message. TBH x-axis of log(#commits) seems reasonable. Even if projects have relatively different commit practices I think, on average, it's a reasonable proxy for net growth, though it's certainly not perfect.

**Comment by cdolfi** [comment]
<p>So I actually do not view this as a double count, I view this as counting something completely different. this is inspired by the quote </p><p> </p><p>"...most developers are interested in using and participating in the largest projects, and the projects with the most developers are more likely to quickly fix bugs, add features and work reliably across the largest number of platforms."</p><p> </p><p>This is looking at all of the actions around prs and issues. I feel like there is a difference between the existence of a pr and issue, and the full development cycle around them (opening, commenting, closing/merging). The question is that does this provide a better view into "project velocity" or the 1 dimensional view is better. </p><p> </p><p>Note: The merged vs closed problem is handled in the actions query. There is no double count for merged PRs  </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/221/discussion/#comment-1672190684'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>Yeah in talks with sean on this. There is some augur bug happening here </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/221/discussion/#comment-1672190718'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>Wait actually realized I thought you were responding to something else. Not sure what you mean by a "Double count" here. This doesnt take into account "at time t", this is just counting the number of each action through all time. So the goals of these values are not to get the number of open issues, prs, etc at a specific time T, but to count the actions themselves </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/221/discussion/#comment-1672190684'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>I like this idea of having a toggle on the view</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/221/discussion/#comment-1672190736'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>The merged vs closed problem is handled in the actions query. There is no double count for merged PRs</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/221/discussion/#comment-1672190779'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>What is LoC? </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/221/discussion/#comment-1672190828'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
@JamesKunstle This is the summery I am getting from your comments, let me know if a missing or misinterpreting anything: 

x axis: log(commits) 
y axis: PR and issue Actions (open closed merged) with user inputed weights and the ability to toggle between log or not 

let me know and ill start building the viz!

**Comment by JamesKunstle** [comment]
<p>++ nice</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/221/discussion/#comment-1672190718'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>Ah awesome, that's super nice.</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/221/discussion/#comment-1672190779'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>Lines of Code. Since commits are only representative of a change occurring, and not how large of a change, LoC could be a useful toggle-able perspective. </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/221/discussion/#comment-1672190828'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>Ah makes sense. That would involve integrating another query into this visualization, which im not against. Im going to do the first time pass at the viz with just commits and we can see if we want to add another user input. RN its up to 6 which is twice as much as any of our other ones so I want to see how overwhelming it is or isnt </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/221/discussion/#comment-1672190828'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>++ sounds great. We'll probably have to go through an iteration of query optimization as well- the materialized view query took a while when I ran this notebook locally. Pre-aggregating in SQL is probably faster, and if it's not fast enough, we can do separate queries on the respective tables. </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/221/discussion/#comment-1672190828'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesKunstle** [comment]
<p>@cdolfi Yes, that sounds exactly right. Very very excited for this.</p>

**Comment by JamesKunstle** [comment]
<p>The query throughput time might be fast (how long it takes for the database to receive a request, prepare a response, and begin sending the response) but, at least in the example in the beginning of the notebook, there are still 1.6 million rows that need to travel over the wire. If they can pre-aggregate the statistics that we need based on this table, and we just have to request the view of it, that'd be sick. Not sure how much that'd take to do.</p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/221/discussion/#comment-1672190828'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
<p>As we use this query more there might be a few preprocessing steps that are consistent for a few of the vizs and we make them into their own queries based on the materialized view. Lets come back to this idea (if nothing more comes from the josh/sean convo) after we have a few more vizes in that use it and see if there is some consistencies that come up </p>

---

 <a href='https://app.reviewnb.com/oss-aspen/Rappel/pull/221/discussion/#comment-1672190828'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cdolfi** [comment]
@JamesKunstle updates in, from my side ready to merge

**Review by JamesKunstle — APPROVED** [review]
lgtm, we've reviewed and talked through this for a while.

**Pull request merged**
